# Generated by Django 5.1.7 on 2025-05-23 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial_categories'),
        ('shop', '0003_alter_product_options_and_more'),
    ]

    operations = [
    ]
